### ISSUE TITLE
How to read incoming messages

### ISSUE THREAD

**Issue by adiltonvalaszek** [dimaskiddo/go-whatsapp-rest#1]
Hi, I would like to know how I can read the received messages?

**Comment by adiltonvalaszek** [comment]
I solved adding Handler in the helper. I'm closing this issue.

**Comment by sthales** [comment]
@adiltonvalaszek can you share your solution?

**Comment by dimaskiddo** [comment]
You can see the examples in [go-whatsapp-cli](https://github.com/dimaskiddo/go-whatsapp-cli) or the [go-whatsapp](https://github.com/dimaskiddo/go-whatsapp) package it self about echoing a message
