### ISSUE TITLE
Can you help me for installing

### ISSUE THREAD

**Issue by rvp98** [dimaskiddo/go-whatsapp-rest#10]
![image](https://user-images.githubusercontent.com/54128956/63482262-7492fb80-c4c2-11e9-95e5-6a02387a557c.png)

i get this error on `make ensure`

**Comment by dimaskiddo** [comment]
@rvp98 Can you try to use git-bash, since it's in Windows and the Makefile does have an unix or linux command i think it's better to use git-bash
