### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by bamjohn2222** [dimaskiddo/go-whatsapp-rest#13]
I a trying to do this on my machine but somehow the documentation is not clear to me. I am completely new to GoLang and I also intend on improving the docs for further usage.
Help me run this on my local machine. Thanks

**Comment by bamjohn2222** [comment]
Should I simply use git clone url and run or is there anything else needed?

**Comment by dimaskiddo** [comment]
You can use git bash if you are using windows and please makesure all dependencies are installed

**Comment by dimaskiddo** [comment]
Clossing this issue due to no activities or updates, please feel free to reopen this issue
