### ISSUE TITLE
api return unauthorized method GET

### ISSUE THREAD

**Issue by Lucipher** [dimaskiddo/go-whatsapp-rest#14]
call /api/v1/whatsapp/auth?Username=xxx&Password=xxxx
return unauthorized method GET at URI /api/v1/whatsapp/auth

**Comment by dimaskiddo** [comment]
The auth is using basic auth method, please use basic auth method

username is your phone number as jID and the basic auth password you can find it in the hlp/config.go as there is no override for password in the config file in share/etc/*.yaml file

**Comment by Lucipher** [comment]
> The auth is using basic auth method, please use basic auth method
> 
> username is your phone number as jID and the basic auth password you can find it in the hlp/config.go as there is no override for password in the config file in share/etc/*.yaml file

Thanks very much! It works nice.
