### ISSUE TITLE
write: connection reset by peer

### ISSUE THREAD

**Issue by Lucipher** [dimaskiddo/go-whatsapp-rest#15]
error writing to websocket: write tcp 192.168.3.155:36558->160.240.15.53:443: write: connection reset by peer

**Comment by Lucipher** [comment]
@dimaskiddo  how to reconnect websocket after websocket error ?

**Comment by dimaskiddo** [comment]
@Lucipher you can try to reconnect by hitting the login API, it should closed the old connection and created a new one

**Comment by dimaskiddo** [comment]
Clossing this issue due to no activities or updates, please feel free to reopen this issue
