### ISSUE TITLE
sample of working?

### ISSUE THREAD

**Issue by northbearleung** [dimaskiddo/go-whatsapp-rest#16]
How to make it work ? 
I startup the port 3000 , seems installation completed. 
But what's next? it's suppose a websocket server or web server to trigger login Scan QRCODE event ? 
I am new to it . sorry for silly question I raised!

**Comment by dimaskiddo** [comment]
@northbearleung swagger as API docs will be integrated soon, currently you need to read the flow by your self first, sorry

**Comment by saxtorinc** [comment]
ive called /login?

**Comment by dimaskiddo** [comment]
@saxtorinc Please read again the README.md it has the default Router Base Path, you should read it in the config file

**Comment by dhruvsaraiya** [comment]
Have you added API docs?

**Comment by dimaskiddo** [comment]
@dhruvsaraiya not yet, i still have a lot of works to do. Sorry

**Comment by ibnux** [comment]
@dimaskiddo can you enable the discussion in this repo, so people who only ask, not the issue can discuss in there

**Comment by dimaskiddo** [comment]
Pak @ibnux will try to enabling it
