### ISSUE TITLE
Receive and echo using WAMessageText Helper

### ISSUE THREAD

**Issue by breadpanz** [dimaskiddo/go-whatsapp-rest#2]
I a newbie in go so, please bear with me.
I would really appreciate if we can add the message handler in the helper, like how he does with this one #1 cause, I was confused when there's an incoming message how can I trace if It is in the specific JWT Claims.

**Comment by dimaskiddo** [comment]
I think you can see the other repositories where it's become a bot-like for whatsapp in [go-whatsapp-cli](https://github.com/dimaskiddo/go-whatsapp-cli), mostly it solved by attaching a handler to the whatsapp connection (wac), more example how to echo message can also found in [go-whatsapp](https://github.com/dimaskiddo/go-whatsapp) examples

**Comment by breadpanz** [comment]
wow thank you very much I miss this repo so, I guess this will solve everything [go-whatsapp-cli](https://github.com/dimaskiddo/go-whatsapp-cli).
