### ISSUE TITLE
Implement build on Dockerfile

### ISSUE THREAD

**Issue by tarikhagustia** [dimaskiddo/go-whatsapp-rest#20]
i think on Docker file, should add build function

**Comment by dimaskiddo** [comment]
siaap mas, sekalian mau di perbaiki ada bug sejak WA api memblock beberapa fungsi hehe

**Comment by tarikhagustia** [comment]
iya, saya juga baru kena pas restart [https://github.com/Rhymen/go-whatsapp/issues/305](https://github.com/Rhymen/go-whatsapp/issues/305)

**Comment by dimaskiddo** [comment]
Multistage Dockerfile implemented image also available in dimaskiddo/go-whatsapp-rest, client version also now configurable via config file or environment variables

Thanks 😄
