### ISSUE TITLE
not allowed method GET at URI /api/v1/whatsapp/login

### ISSUE THREAD

**Issue by sicenul** [dimaskiddo/go-whatsapp-rest#23]
I try your docker and can use the auth endpoint and get the token.

$ docker run -p 3000:3000 gowa

accesing http://localhost/api/v1/whatsapp/auth and using basic auth method can get me the token.
But how to use the other endpoint, such as: whatsapp/login, whatsapp/send/text, etc. Where should I put the token?

Please enlighten me.
Thanks

**Comment by dimaskiddo** [comment]
Auth endpoint is used to get the JWT Token, so in order to use the token please make sure you are using Bearer <TOKEN> in Authorization Header

For the endpoints method you can check it in routes.go file
and It should be POST method

**Comment by sicenul** [comment]
Great, it work. Now I can logged in using qrcode provided by /login endpoint. But it doesn't return anything, just info on my android that "Last active today at ... Started in .... Go WhatsApp REST".

What's next if I want to use /send/text endpoint?
Can I use postman/insomnia to test it, how?

**Comment by dimaskiddo** [comment]
I have the Postman collection but it's not for public you migh contact me in private
Or you can wait until swagger doc is integrated

**Comment by sicenul** [comment]
Is it for free? :smiley: 
How can I contact you in private?

**Comment by dimaskiddo** [comment]
Yes it's free, but you need convince me about what do you use it for 😄

**Comment by dimaskiddo** [comment]
I closed this issue due to inactivity
Feel free to open back this issue

**Comment by the-jojo-jj** [comment]
yes, plasa share the Postman collection.

**Comment by the-jojo-jj** [comment]
yes, please share the Postman collection.
