### ISSUE TITLE
Error, I can not send the picture.

### ISSUE THREAD

**Issue by Diden05** [dimaskiddo/go-whatsapp-rest#25]
Hi!
Trying to send a picture,
'Content-Type: multipart/form-data'

    $fields = [
        'msisdn'=> $_REQUEST['msisdn'] . '@s.whatsapp.net',
        'message'=> $_REQUEST['message'],
        'image' => new \CurlFile('C__fakepath_shampinony-7.png', 'image/png', 'filename.png')
    ];
    $cURLConnection = curl_init('http://172.16.0.101:3000/api/v1/whatsapp/send/image');
    curl_setopt($cURLConnection, CURLOPT_POST, 1);
    curl_setopt($cURLConnection, CURLOPT_POSTFIELDS, $fields);
    curl_setopt($cURLConnection, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($cURLConnection, CURLOPT_HTTPHEADER, $header);

in response I get

[status] => 
[code] => 500
[message] => Internal Server Error
[error] => image upload failed: upload responsed with %!d(float64=404)

**Comment by Diden05** [comment]
same thing when trying to send audio
    [error] => audio upload failed: upload responsed with %!d(float64=404)

**Comment by sthales** [comment]
https://github.com/Rhymen/go-whatsapp/pull/317

**Comment by Diden05** [comment]
> [Rhymen/go-whatsapp#317](https://github.com/Rhymen/go-whatsapp/pull/317)

Will there be an update to the version of the library used?

**Comment by dimaskiddo** [comment]
Yes, will be updated soon @Diden05 
Thanks @sthales for the information of updated logic for media content 👍

**Comment by dimaskiddo** [comment]
Sorry for the late response all, this bug just closed by the update of commit f484142
