### ISSUE TITLE
How to get a GroupId?

### ISSUE THREAD

**Issue by gutoscherer** [dimaskiddo/go-whatsapp-rest#28]
Hi,

I'm trying to send messages to a specific group, but I need a groupId, like 55XXXXXXXXXX-XXXXXXXX@g.us, but I don't know how to get this Id. Can you help me?

Thanks

**Comment by dimaskiddo** [comment]
It will be little bit hard but GID is combination between user JID and Timestamp of created group in Unix Timestamp

The solution is by adding handler listener to get or read the messaged from the group, or if the group was created by your self then may be you can use the combination as i said before

**Comment by gutoscherer** [comment]
Thanks @dimaskiddo, I made it reading a message in the group and getting the infos.
