### ISSUE TITLE
HandleMessages

### ISSUE THREAD

**Issue by arisawali2014** [dimaskiddo/go-whatsapp-rest#30]
is there a way to make handle messages?

**Comment by dimaskiddo** [comment]
@arisawali2014 i split the example to the other repository to be a bot like in [dimaskiddo/go-whatsapp-cli](https://github.com/dimaskiddo/go-whatsapp-cli), may be you can see it there

**Comment by arisawali2014** [comment]
the thing is how to append into the route?

**Comment by irvanrahadhian** [comment]
@arisawali2014 if what you want is to handle incoming message, you can try to add handler at helper, or you can see the example at the other repo just like @dimaskiddo said.

**Comment by dimaskiddo** [comment]
@arisawali2014 handlers run in connection levels, it's attached to it. So if you want to integrate it in route may be you can integrate in helper code at log in function

@irvanrahadhian thanks for helping to explain :smile:
