### ISSUE TITLE
Always logout

### ISSUE THREAD

**Issue by ibnux** [dimaskiddo/go-whatsapp-rest#31]
so after trying and running, it seems every 3 days need to scan barcode
how to make session never expired?

i try using cronjob, every 1 hour will send message, and still logout every 2-3 days

**Comment by irvanrahadhian** [comment]
Hey i have the same issue like this, but only re scan when the client doesn't have internet access (or bad internet connection) and trying to re loggin again.

the longest client and bot working and running is 1 week.

**Comment by dimaskiddo** [comment]
it's because of bad connections so the websocket connections is terminated.
Current best way is to check if gob sessions file still valid, if it's valid then you can integrate internal go-cron to relogin all saved sessions by calling the relogin functions, there is a pull request of it but currently i'am not merging it due to some my internal conecern

**Comment by ibnux** [comment]
i see that, when i get this error
> couldn't dial whatsapp web websocket: dial tcp: lookup web.whatsapp.com: no such host

then the session will be deleted, and need to relogin
the logic is delete file session then request again, and that when request failed, the session file already deleted 

but i am not expert with Rhymen/go-whatsapp package, so i think that should be like that, because Dimas create like that :D

**Comment by dimaskiddo** [comment]
I'll added connection HandleError Handler (this might help to resolve issue of websocket error in case of unstable connection) later, but need help for testing if you don't mind sir @ibnux and sir @irvanrahadhian hehe

**Comment by ibnux** [comment]
Oke, no problem

I use this project for broadcasting message to RT residents 😀

And for chatbot using botlibre, if someone reply the message 😂

Temporary fixing I commented os.Remove at hlp/libs/whatsapp.go except at logout function

**Comment by irvanrahadhian** [comment]
> I'll added connection HandleError Handler (this might help to resolve issue of websocket error in case of unstable connection) later, but need help for testing if you don't mind sir @ibnux and sir @irvanrahadhian hehe

Oke and thank you Mas @dimaskiddo

**Comment by dimaskiddo** [comment]
Thanks everyone for helping me to test this,
I've commit the HandleError Handler by commit with id adf8d41

I'am sorry if there some directory changes, so it might be need for you to refork the repo :pray:
Thank's and i hope this work to solve the issue

**Comment by ibnux** [comment]
Thanks @dimaskiddo for your hard work 👍🤝
merging not much conflict, and directory follow your update
