### ISSUE TITLE
Can't send image

### ISSUE THREAD

**Issue by irvanrahadhian** [dimaskiddo/go-whatsapp-rest#33]
Hello mas @dimaskiddo , I'm having issue that i can't send images through the endpoint send image.
Got timeout error when post to https://mmh.whatsapp.net/mms/image

here is the error log : 

`send image upload failed: Post "https://mmh.whatsapp.net/mms/image/oe0QfWAk_hk3BTVDpkXvO9wGyicJ58J3R_Y_LS2wPQA=?auth=AWSzkeJZKt6eLarpXISRavMOmksci9p2GggXFmg03Bpbq8QKHqzviNZqz2c&token=oe0QfWAk_hk3BTVDpkXvO9wGyicJ58J3R_Y_LS2wPQA%3D": net/http: TLS handshake timeout
{"label":"http-access","level":"error","msg":"image upload failed: post \"https://mmh.whatsapp.net/mms/image/oe0qfwak_hk3btvdpkxvo9wgyicj58j3r_y_ls2wpqa=?auth=awszkejzkt6elarpxisravmomksci9p2gggxfmg03bpbq8qkhqzvinzqz2c\u0026token=oe0qfwak_hk3btvdpkxvo9wgyicj58j3r_y_ls2wpqa%3d\": net/http: tls handshake timeout","service":"go-whatsapp-rest","time":"2020-10-13T15:51:22.904043384+07:00"}`

**Comment by dimaskiddo** [comment]
@irvanrahadhian i think it's your DNS or Connection problem, make sure it's ok to connect there or the DNS is resolved. I'll also check on my side

**Comment by irvanrahadhian** [comment]
Oke solved @dimaskiddo , you're right its the Connection problem from my cloud server. btw thank for the updated code, so far it's going smooth without having disconnected and have to rescan. great work

**Comment by dimaskiddo** [comment]
Thanks for testing it. Nice to know if it's work well 😄

**Comment by the-jojo-jj** [comment]
@irvanrahadhian @dimaskiddo hi guys, since im very new at golang, would you guys help me please with postman to send txt and image?

i've manage to login and scan qr, but have no clue what is next. 
thanks.

**Comment by dimaskiddo** [comment]
@the-jojo-jj please explain with well your usage of this source code if you need the postman, there are not permitted to sell this source code

**Comment by the-jojo-jj** [comment]
Actually,  We are building a public information system through WhatsApp to help people during this Covid period manage queues. We need a send image to send qrcode like this http://rsudalihsan.jabarprov.go.id/assets/uploads/2018/08/qqrcode_768.png.

Please help.

**Comment by dimaskiddo** [comment]
Sorry instead continuing this issue for non related topic, you can mail me then explain what do you want to do included the scenario.
But for some ot the week i'll be really slow response, cause there's also another gov project in my office that needs to be done.
Thank's @the-jojo-jj
