### ISSUE TITLE
Disconnecting the device and the lifetime of the token

### ISSUE THREAD

**Issue by wagnerfillio** [dimaskiddo/go-whatsapp-rest#35]
@dimaskiddo,

Sign in successfully

I retrieved the qrcode and read it with the mobile device.

I sent the message successfully!

But then I was disconnected.

My question is:
How do I not get disconnected?

What is the lifetime of the token, where can I set a time for it?

Another question is how do I change the customer's name, which appears in the device's Whatsapp settings.

**Comment by dimaskiddo** [comment]
Hai @wagnerfillio token lifetime is defined as configurable options in yaml file, you can see for the variable name in pkg/server/config.go the default is only for 24h

**Comment by dimaskiddo** [comment]
I'am clossing this issue due to no next discussion, please feel free to re open.
Thanks
