### ISSUE TITLE
healthcheck is unhealthy

### ISSUE THREAD

**Issue by sicenul** [dimaskiddo/go-whatsapp-rest#37]
Hello,
My docker status is unhealthy, but I can send message successfully and without any problem.
Why is it unhealthy?
```
"go-whatsapp-rest"       About a minute ago   Up About a minute (unhealthy)   0.0.0.0:3000->3000/tcp
```

**Comment by dimaskiddo** [comment]
@sicenul I'll try to recheck, meanwhile may be you can make sure that you already using the latest image or source code

**Comment by sicenul** [comment]
FYI, I already use the latest source code.

**Comment by dimaskiddo** [comment]
Okays i see this, sorry for slow response

**Comment by dimaskiddo** [comment]
@sicenul i already test but not yet push the fix, can you help me to try build the Docker images by changging this line
https://github.com/dimaskiddo/go-whatsapp-rest/blob/d6a00a048d98298c894d12e2853d9e1b0c9f71ab/Dockerfile#L31

to be something like this
`HEALTHCHECK --interval=5s --timeout=3s CMD ["sh", "-c", "curl http://127.0.0.1:3000${PRODUCTION_ROUTER_BASE_PATH}/health"] || exit 1`

An try to build the Docker images, PR will be welcome :smile:

**Comment by sicenul** [comment]
great thanks, it worked and PR sent. I'm closing this.
