### ISSUE TITLE
panic: runtime error: invalid memory address or nil  pointer dereference

### ISSUE THREAD

**Issue by baddwin** [dimaskiddo/go-whatsapp-rest#38]
Halo mas, saya belum belajar banyak di golang, mohon bantuannya, ada kejadian error saat memanggil route login beberapa kali secara cepat berurutan

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7bb286]

goroutine 1833 [running]:
github.com/Rhymen/go-whatsapp.(*Conn).AdminTest(0x0, 0x30, 0xc0004820c0, 0x12)
       ~/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200917103834-23c68e1d6342/conn.go:222 +0x26
github.com/dimaskiddo/go-whatsapp-rest/pkg/whatsapp.WATestPing(0x0, 0xc00018cde0, 0xc00028a300)
        ~/go-whatsapp-rest/pkg/whatsapp/whatsapp.go:127 +0x2f
github.com/dimaskiddo/go-whatsapp-rest/pkg/whatsapp.WASessionConnect(0xc00028a300, 0xd, 0x2, 0x7f3, 0xf, 0x5, 0xc000280240, 0x21, 0x1e, 0xc0003b0300, ...)
        ~/go-whatsapp-rest/pkg/whatsapp/whatsapp.go:242 +0x32e
github.com/dimaskiddo/go-whatsapp-rest/internal/whatsapp.WhatsAppLogin.func1(0xc00028a300, 0xd, 0xa9b770, 0x4, 0x1e, 0x5, 0x2, 0x7f3, 0xf, 0xc000280240, ...)
       ~/go-whatsapp-rest/internal/whatsapp/whatsapp.go:138 +0xae
created by github.com/dimaskiddo/go-whatsapp-rest/internal/whatsapp.WhatsAppLogin
       ~/go-whatsapp-rest/internal/whatsapp/whatsapp.go:137 +0x592
exit status 2
```

**Comment by norazlan** [comment]
try delete these lines and run/build again: https://github.com/dimaskiddo/go-whatsapp-rest/blob/d6a00a048d98298c894d12e2853d9e1b0c9f71ab/pkg/whatsapp/whatsapp.go#L237-L241

**Comment by dimaskiddo** [comment]
it's known bug as a race condition sometimes happened when multi login is used. The error shown because wac[jid] is containing null memory reference, since may be the connection has been lost or something else. You can follow @norazlan recommendation if you like by disabling "Ping" test to WA Server

**Comment by dimaskiddo** [comment]
Clossing this issue due to inactivity.
Feel free to reopen this issue, thanks

**Comment by Diden05** [comment]
Maybe it's better to add a check to WATestPing?

**Comment by dimaskiddo** [comment]
How is the proposal do you have to do that @Diden05 ?
