### ISSUE TITLE
problem in setting CORS in routerCORS 

### ISSUE THREAD

**Issue by breadpanz** [dimaskiddo/go-whatsapp-rest#4]
It must be w.Header().Set() instead of r.Header.Set()

In line 76 : https://github.com/dimaskiddo/go-whatsapp-rest/blob/master/service/router.go

**Comment by dimaskiddo** [comment]
Thank's for checking it ;)
I reaaly appreciate it

Issue has been fixed in commit [e3fad06](https://github.com/dimaskiddo/go-whatsapp-rest/commit/e3fad06be49e0ba31e0fdca6281e56c2c71e3a9c), clossing this issue
