### ISSUE TITLE
Connection is Invalid

### ISSUE THREAD

**Issue by umerashraf** [dimaskiddo/go-whatsapp-rest#42]
Hello, So first i have done a GET request at : **api/v1/whatsapp/auth**. 
Authorization Bearer:
Username : 92xxxxxxxxxx
Password: **AUTH_BASIC_PASSWORD**

I received the JWT token in response, Then i used that token in Authorization Bearer in : **api/v1/whatsapp/login**, 
I received a QR Code, I scanned it from my whatsapp, and it was fine.
Then i tried **POST** Request to  : **api/v1/whatsapp/send/text**
Header using : **application/x-www-form-urlencoded**
Also Header : Bearer TOKEN
Inside Body added:
```
{
msisdn:92313xxxxxxx@s.whatsapp.net
message:test
quotedid:1
quotedmsg:test
}
```
So irrespective of whichever msisdn or quoteid whether added or not , i still receive same error response.

```
{
    "status": false,
    "code": 500,
    "message": "Internal Server Error",
    "error": "connection is invalid"
}

```
Can you guide me where i am wrong in this approach ?

**Comment by baddwin** [comment]
@umerashraf double check the token you pass to the request. I've once got similar issue, and turned out it's just because of incomplete token.

**Comment by ibnux** [comment]
Sometimes you need to send request to endpoint /login again

**Comment by dimaskiddo** [comment]
and make sure your to change the WhatsApp Client version in:
https://github.com/dimaskiddo/go-whatsapp-rest/blob/948fcc880ffebc381c31c62afa86ff1d31bf6399/config/production.yaml#L21-L23

**Comment by dimaskiddo** [comment]
Clossing this issue due to inactivity.
Feel free to reopen this issue, thanks
