### ISSUE TITLE
Using modified Rhymen go-whatsapp

### ISSUE THREAD

**Issue by hrizal** [dimaskiddo/go-whatsapp-rest#43]
Hi Dimas,

I tried to use the modified Rhymen whatsapp library, but it always refers to the released version.
how do if i want to use the modified WhatsApp library?

Nuhun ah, kamu keren

**Comment by dimaskiddo** [comment]
Halo @hrizal 

you can change any github.com/Rhymen/go-whatsapp reference to your or custom repo (this might be use in internal controller or helper library, recommendation try to use find and grep command), then use make init to reinitialize the go.mod

Sami-sami kang hehe

**Comment by hrizal** [comment]
go get github.com/Rhymen/go-whatsapp@master
 
 hehehe, ok, thanks
