### ISSUE TITLE
Error send first message

### ISSUE THREAD

**Issue by danielspk** [dimaskiddo/go-whatsapp-rest#44]
Hello. I see the WASendWithMutex() method use a scope assignment which is not correct:

Original

```go
func WASendWithMutex(jid string, content interface{}) (string, error) {
	mutex, ok := wacMutex[jid]

	if !ok {
		mutex := &sync.Mutex{} // <-- FIX?
		wacMutex[jid] = mutex
	}

	mutex.Lock() // <-- error if ok is false

	// ...
}
```

Proposal:

```go
func WASendWithMutex(jid string, content interface{}) (string, error) {
	mutex, ok := wacMutex[jid]

	if !ok {
		mutex = &sync.Mutex{} // <-- CHANGE
		wacMutex[jid] = mutex
	}

	mutex.Lock() // <-- work is ok is false

	// ...
}
```

I am right?

**Comment by dimaskiddo** [comment]
Ah i see...
You should be correct, can you create a pull request?

**Comment by danielspk** [comment]
Yes, this change is made in a development and it works satisfactorily. During the day I create a pull request. Thanks @dimaskiddo

**Comment by dimaskiddo** [comment]
Thank you so much @danielspk it's has been merged
I'll close this issue then
