### ISSUE TITLE
Connection automatically lost after an hour

### ISSUE THREAD

**Issue by janamcroods** [dimaskiddo/go-whatsapp-rest#46]
from last 2-3 months i have experienced strange issue that once scanned QR Code and sending message works till 1-2 hours perfectly but after that it does not works we need to scan again, there is no internet issue there.

whatsapp failed to write message: invalid websocket

{
    "status": false,
    "code": 500,
    "message": "Internal Server Error",
    "error": "connection is invalid"
}

**Comment by dimaskiddo** [comment]
@janamcroods pelase make sure your connection is stable, unstable connection will result lost session since WhatsApp Web is using Websocket protocol

**Comment by dimaskiddo** [comment]
Clossed due to inactivity
Feel free to reopen
