### ISSUE TITLE
akses api

### ISSUE THREAD

**Issue by diazzaid** [dimaskiddo/go-whatsapp-rest#48]
mas sy mau tanya, 
ketika sudah di make run, sy coba akses https://localhost:3000
nah untuk akses api nya bagai mana ya? hehe
sy coba /login
/ auth
statusnya not found..

**Comment by ibnux** [comment]
Silahkan check bagian diskusi repo ini

Sudah saya tulis cara pakainya

**Comment by diazzaid** [comment]
> Silahkan check bagian diskusi repo ini
> 
> Sudah saya tulis cara pakainya

oia pa , sudah ada hehe 
terima kasih
