### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by ArivhaySoft** [dimaskiddo/go-whatsapp-rest#49]
{
    "status": false,
    "code": 500,
    "message": "Internal Server Error",
    "error": "error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}\n"
}

**Comment by dimaskiddo** [comment]
Please upgrade the WhatsApp Client Version in config/production.yaml
https://github.com/dimaskiddo/go-whatsapp-rest/blob/c8a8430e8dd06cf9dfa9502c49b5ba7b2a09ad8d/config/production.yaml#L20-L23

Or config/development.yaml
https://github.com/dimaskiddo/go-whatsapp-rest/blob/c8a8430e8dd06cf9dfa9502c49b5ba7b2a09ad8d/config/development.yaml#L20-L23

**Comment by punyahenry** [comment]
{"label":"server-http","level":"info","msg":"server master started at pid 24687","service":"go-whatsapp-rest","time":2021-06-25T20:48:14.992171859+07:00"}
{"label":"server-http","level":"info","msg":"server worker started at pid 24687 listening on 0.0.0.0:3000","service":"go-whatsapp-rest","time":2021-06-25T20:48:14.992834039+07:00"}
{"label":"whatsapp-session-init","level":"info","msg":"whatsapp version 2.2114.10","service":"go-whatsapp-rest","time":"2021-06-25T20:48:19.110057301+07:00"}
{"label":"http-access","level":"error","msg":"error decoding login resp: json: cannot unmarshal array into go value of type map[string]interface {}\n","service":"go-whatsapp-rest","time":"2021-06-25T20:48:19.30532754+07:00"}

still not working it's same issue?

**Comment by ibnux** [comment]
@punyahenry are the WhatsApp in the phone is upgraded to latest version too?

**Comment by punyahenry** [comment]
> @punyahenry are the WhatsApp in the phone is upgraded to latest version too?

the issue qr not showing, in store folder no obj files

**Comment by dimaskiddo** [comment]
@punyahenry at your log it's shown that your configuration still using old WhatsApp Client Version (2.2114.10), please update WhatsApp Client Version in yaml configuration file to the latest WhatsApp Web Version (currently it's 2.213.7)

**Comment by punyahenry** [comment]
@dimaskiddo thanks.. now it's working with new version

**Comment by irvanrahadhian** [comment]
latest version web whatsapp : 
WHATSAPP_CLIENT_VERSION_MAJOR: 2
WHATSAPP_CLIENT_VERSION_MINOR: 2123
WHATSAPP_CLIENT_VERSION_BUILD: 7

**Comment by ArivhaySoft** [comment]
an error occurs again, how to check the latest version? @dimaskiddo

**Comment by ArivhaySoft** [comment]
> an error occurs again, how to check the latest version? @dimaskiddo

latest version web whatsapp :
WHATSAPP_CLIENT_VERSION_MAJOR: 2
WHATSAPP_CLIENT_VERSION_MINOR: 2142
WHATSAPP_CLIENT_VERSION_BUILD: 12

I use this and it works fine :D

**Comment by punyahenry** [comment]
Looks good.. thanks.. Anyway how do you get whatsapp client version?

**Comment by dimaskiddo** [comment]
Open your WhatsWeb Desktop and see it in Help -> About
