### ISSUE TITLE
Problems getting chats

### ISSUE THREAD

**Issue by sthales** [dimaskiddo/go-whatsapp-rest#5]
With the Chats func (contact.go - Chats()) I was able to get the list of chats with contact names etc. but it works only with iOS, when I log in using Android, it returns "null".
Does anyone know how can I get the chat list on all platforms?

**Comment by dimaskiddo** [comment]
It seems more related to [Rhymen/go-whatsapp](https://github.com/Rhymen/go-whatsapp), you might need to move this issue there, and i think currently it's not fully supported, or may be go-whatsapp team have more detail about it

Thank's
