### ISSUE TITLE
How can I use this in production?

### ISSUE THREAD

**Issue by luannsr12** [dimaskiddo/go-whatsapp-rest#50]
How can I use this in production? Another question, is it possible to connect more than one device with this API?

Do you have any documentation to use?

**Comment by ibnux** [comment]
Check discussion page

I create tutorial

And yes it can use multiple phone number

I already use it for production

**Comment by dimaskiddo** [comment]
As pak @ibnux says it's already discussion page for how to use this @luannsr12
