### ISSUE TITLE
Error Send Message

### ISSUE THREAD

**Issue by ahmadyusri** [dimaskiddo/go-whatsapp-rest#52]
{"label":"whatsapp-error-handler","level":"error","msg":"id axxxx caught an error, message type not implemented","service":"go-whatsapp-rest","time":"2021-09-04T20:38:18.9456114+07:00"}

{"label":"whatsapp-error-handler","level":"error","msg":"id axxxx caught an error, message type not implemented","service":"go-whatsapp-rest","time":"2021-09-04T20:38:19.0144961+07:00"}

{"label":"whatsapp-error-handler","level":"error","msg":"id axxxx caught an error, message type not implemented","service":"go-whatsapp-rest","time":"2021-09-04T20:38:19.0148555+07:00"}

{"label":"whatsapp-error-handler","level":"error","msg":"id axxxx caught an error, message type not implemented","service":"go-whatsapp-rest","time":"2021-09-04T20:38:19.0148649+07:00"}

{"label":"whatsapp-error-handler","level":"error","msg":"id axxxx caught an error, message type not implemented","service":"go-whatsapp-rest","time":"2021-09-04T20:38:19.0148933+07:00"}

{"label":"whatsapp-error-handler","level":"error","msg":"id axxxx caught an error, message type not implemented","service":"go-whatsapp-rest","time":"2021-09-04T20:38:19.1168347+07:00"}

{"label":"whatsapp-error-handler","level":"error","msg":"id axxxx caught an error, message type not implemented","service":"go-whatsapp-rest","time":"2021-09-04T20:38:19.1172436+07:00"}

**Comment by dimaskiddo** [comment]
Hello @ahmadyusri can you please more spesific about the error like what endpoint did you hit and the payload that your are trying to send?

**Comment by dimaskiddo** [comment]
Clossing this issue since no activities or response
