### ISSUE TITLE
couldn't dial whatsapp web websocket: websocket: bad handshake

### ISSUE THREAD

**Issue by punyahenry** [dimaskiddo/go-whatsapp-rest#55]
Hi anyone have facing same issue like this?

{"label":"server-http","level":"info","msg":"server master started at pid 13635","service":"go-whatsapp-rest","time":2022-04-12T10:59:53.042902018+07:00"}
{"label":"server-http","level":"info","msg":"server worker started at pid 13635 listening on 0.0.0.0:3000","service":"go-whatsapp-rest","time":2022-04-12T10:59:53.043223705+07:00"}
{"label":"http-access","level":"error","msg":"connection is invalid","service":"go-whatsapp-rest","time":"2022-04-12T11:00:03.265141021+07:00"}
{"label":"whatsapp-session-init","level":"info","msg":"whatsapp version 2.2147.16","service":"go-whatsapp-rest","time":"2022-04-12T11:00:52.442825304+07:00"}
{"label":"http-access","level":"error","msg":"couldn't dial whatsapp web websocket: websocket: bad handshake","service":"go-whatsapp-rest","time":"2022-04-12T11:00:57.874909569+07:00"}

**Comment by ibnux** [comment]
kadang punya saya kaya gini juga

Koneksi ke WhatsApp kayanya gagal.

Tapi ntar lancar lagi

Coba flush dns atau restart dns lokal.

Coba ping juga ke web.whatsap.com

**Comment by ibnux** [comment]
sepertinya sudah harus ke Whatsapp baru yang pake multi device. udah ga bisa yang ini

**Comment by ibnux** [comment]
Solusinya downgrade WhatsApp apk.

Atau pindah ke WhatsApp API lain

Mas Dimas mungkin lagi sibuk, belum sempat pindah ke multidevice.

Ini hasil fork saya, tapi sayangnya ngga bisa multi session

https://github.com/ibnux/go-whatsapp-web-multidevice

**Comment by dimaskiddo** [comment]
Terima kasih Pak @ibnux mas @punyahenry 
Betul seperti yang disampaikan oleh pak @ibnux sebelumnya, dikarenakan WA sudah mulai beralih ke Multi-Device oleh karena itu perlu dilakukan recode dimana kemungkinan akan berpindah ke repository baru

Hal ini dikerenakan cara kerja library lama dengan yang baru dengan support Multi Device sangatlah berbeda, dari mulai event handling bahkan cara berkirim pesannya yang saat ini full proto buff. Oleh karena itu mohon maaf sebelumnya karena belum dapat mengupdate ataupun membuat repository baru atas pembaharuan yang terjadi.

Mohon doanya agar saya bisa kembali aktif development, dikarenakan saat ini di dunia nyata juga sedang banyak yang harus dikerjakan. Terima kasih atas bantuan dan perhatian kawan-kawan semua.

**Comment by dimaskiddo** [comment]
Bagi yang menggunakan Multi Device library dari tulir dan menginginkan Multi Session itu dapat dilakukan dengan mensplit SQLite file dan Client Connector menjadi sebuah Array Type Struct terlebih dahulu yang mana nanti ID Array dapat digunakan untuk memilih Session mana yang akan digunakan. Secara sederhana mungkin seperti itu

**Comment by dimaskiddo** [comment]
Currently still in development for multi-device support, check it out
https://github.com/dimaskiddo/go-whatsapp-multidevice-rest

Thanks 😄 ❤️
