### ISSUE TITLE
error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}

### ISSUE THREAD

**Issue by iileandro** [dimaskiddo/go-whatsapp-rest#6]
Anything wrong with the backend api? Today all my requests are receiving this:

{"status":false,"code":500,"message":"Internal Server Error","error":"error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}\n"}

**Comment by iileandro** [comment]
Until yesterday everything was OK. I've debugged. Look on the image below what we have on response, before the error is thrown: 
 
![shot](https://user-images.githubusercontent.com/17341676/58989894-26bc0080-87bb-11e9-8868-0ea7c63b5a4a.png)

**Comment by iileandro** [comment]
I discovered the cause of the problem. In the vendors libs, the fork you made  from https://github.com/Rhymen/go-whatsapp, in conn.go you call wss://w{n}.web.whatsapp.com/ws , where {n} is a random int between 1 and 8. I tried to access the URL https://w3.web.whatsapp.com/ for example, and the QR-Code there doesn't load. I think it's broken. So I removed this subdomain (only wss://web.whatsapp.com) and now it's OK.

**Comment by dimaskiddo** [comment]
Thanks for the issues update, i'll try to update the base library then 🙏

I used the w{n} servers since the main server at web.whatsapp.com sometimes have some issue related to the keepalived connection

Is it stable now when you using the main domain at web.whatsapp.com?

**Comment by breadpanz** [comment]
@dimaskiddo seems like dimaskiddo/go-whatsapp also need an update from the forked

**Comment by iileandro** [comment]
> Thanks for the issues update, i'll try to update the base library then 🙏
> 
> I used the w{n} servers since the main server at web.whatsapp.com sometimes have some issue related to the keepalived connection
> 
> Is it stable now when you using the main domain at web.whatsapp.com?

yes. It seems to be ok now. I sent a pull request in the base lib. I needed to merge the readme.MD commit from Rhymen/go-whatsapp the commit to the master. For the moment i'm pointing my vendor to my fork to get the fix. When you fix, I will point again to your fork lib.

**Comment by dimaskiddo** [comment]
@iilleandro thanks for the report, i'll soon push the fixes

@breadpanz i'll still waiting another stable version from Rhymen since the updates still related or small fixes that keep continous, i'll keep watch the repo, may be i'll try to push the chat update feature

**Comment by dimaskiddo** [comment]
I'll close this issue, should be fixed in this Commit ID 1851e701e136ee01d0950152c77de2a1eee454a6
