### ISSUE TITLE
undefined: routesInit

### ISSUE THREAD

**Issue by sunuazizrahayu** [dimaskiddo/go-whatsapp-rest#9]
i tried to run with: **go run main.go** and get this error
> \# command-line-arguments
> ./main.go:18:2: undefined: routesInit

if i run with **make run**, there's no error showed, but every route show 404 URI not found

**Comment by breadpanz** [comment]
running main.go only will return many error since it needs to run with all the package connected to it.

every routes means even the index is returning 404? then, I think there's a problem in your config file.

by default the endpoint is like this:

localhost:port/api/v1/whatsapp

**Comment by sunuazizrahayu** [comment]
i think it must added into README file.
and, what's username on password? when i access auth page it showed auth dialog

**Comment by breadpanz** [comment]
Well, In my case, It doesn't even matter if @dimaskiddo will put it in README or not since it's kinda self explanatory of how the rest works. btw, you can input any username with the default password in c_auth.go. you also might want to modify it base on your requirement.

**Comment by sunuazizrahayu** [comment]
thanks @breadpanz !
i hope @dimaskiddo will put them to README and fix about the **routesInit**

**Comment by dimaskiddo** [comment]
Will be fixed after restructuring to the new codebase, thanks

**Comment by dimaskiddo** [comment]
Closing this issue should be fixed in 665c1a0
